### ISSUE TITLE
Your script cannot spam for many times

### ISSUE THREAD

**Issue by myworldbox** [itsDARKSAMA/dark_spam#1]
It can only spam for 10 times; for 100+ times, it is unable to spam.

**Comment by itsDARKSAMA** [comment]
Thanks @myworldbox for your comment  , 
I've already tested the script for many times, the script has proved to be effective in sending more than 2,500 spam ( that is the limit i used ) on a number of applications and on Linux Mangaro distribution, ArcoLinux, Ubuntu.

may It's because of your Python version , or TK ( Tkinter ) / PyAutoGUI / Time

**Comment by myworldbox** [comment]
Bro, during my testing, it paused to send message at about the the tenth message. I am also developing telegram, WhatsApp automation using selenium; do you want to work together? My script is working very good. The only fault is WhatsApp and Tg can detect it as a bot and pause its action.

**Comment by myworldbox** [comment]
My script could boardcast to people on my csv list. If u want to work tgt, I can share the source code to u.
